### ISSUE TITLE
关于容器负载分发的问题

### ISSUE THREAD

**Issue by lxepoo** [AliyunContainerService/Issues#1]
场景：我现在有个集群，只有3台机器，里面有若干应用，过了一段时间，我发现性能不够了，我要加入新机器到集群，来提供更高的负载能力。
然后，我希望加入新机器后，我的应用可以通过重新部署来【重新触发容器分发机制】
让应用的容器尽可能均匀的分布在所有节点上，但现在的集群，是没有这个能力的。

我找到一种方式，我把所有节点都重置一下，然后此时所有应用显示灰色，再逐个点击重新部署，此时会分布在所有节点上，达到预期。

如果这个事情不做，会带来一个问题，就是我虽然加进去一个服务器，但是好像对我缓解资源争抢没有太大帮助？

**Comment by denverdino** [comment]
非常感谢您的反馈，我们会增加针对集群资源利用率的容器重新调度策略。

**Comment by jimmycmh** [comment]
你是希望手工操作还是自动操作？

**Comment by lxepoo** [comment]
@jimmycmh  最好默认的，加每次重新部署时，自动重新分配一次。

**Comment by xianlubird** [comment]
@lxepoo 功能已经上线。 [使用说明](https://help.aliyun.com/document_detail/35432.html)
