### ISSUE TITLE
容器内高并发情景下DNS查询会偶发长延时或失败

### ISSUE THREAD

**Issue by lxepoo** [AliyunContainerService/Issues#2]
我是VPC用户，集群也在VPC里，今天升级到最新的容器服务系统服务后，发现RDS FOR MYSQL好像有点问题，老是报错（无法找到主机），我已经反馈给RDS团队，得出的结论是我的RDS实例性能未到瓶颈，从RDS监控来看，很健康。

然后我联系了VPC团队，希望他们帮助我排查一下看看是否我的网络环境有问题，VPC团队持续帮我PING了一下，未发现解析域名有丢包情况。

再然后我联系了容器团队的   溪恒，排查后基本锁定问题在docker engine的Libnetwork用的dns client出的问题。

我暂时的替代方案是compose里加extra-hosts，强制指向。

此问题波及很广，一切域名在高并发下，DNS都可能解析出错，不仅仅是RDS。望速解决。

**Comment by denverdino** [comment]
我们会定位一下代码问题，谢谢！

**Comment by BSWANG** [comment]
@lxepoo 现在我们已经定位到了问题，并且这个问题在Docker engine 1.11.1 中已经解决，我们会尽快进行1.11的集成和测试并找到绕过这个问题的方法，谢谢你提供这个问题。

**Comment by lxepoo** [comment]
@BSWANG 期待你们解决问题，谢谢。

**Comment by denverdino** [comment]
Details in https://github.com/docker/libnetwork/issues/1113

**Comment by denverdino** [comment]
这个问题存在于1.10.x和1.11.0中，
另外如果远程host不需通过域名很重要，建议可以通过配置extra_host的方式来解决。 在 compose 使用 extra_hosts 的方法如下  https://docs.docker.com/compose/compose-file/#extra-hosts

多谢

**Comment by BSWANG** [comment]
新创建集群1.11.2已经发布了，计划下周会提供老集群的升级功能

**Comment by BSWANG** [comment]
老集群升级的功能已经发布，这个issue我先关闭了，如果升级后还有类似问题也可以随时随时在这个issue上反馈
