### ISSUE TITLE
需要一个routing指定http error 默认页的开关

### ISSUE THREAD

**Issue by lxepoo** [AliyunContainerService/Issues#23]
当前的应用在更新时会出现大约30s的503界面，这个界面给客户看到后会显得很low而且不专业，我们有一套自己风格的HTTP CODE UI，比如400  404 500 501 503等。我们希望能自定义，最好是让我们指定一个URL即可，我们可以丢OSS里一堆静态页面来产生固定URL。

**Comment by toolchainx** [comment]
这个功能，我们会通过自定义routing的功能来做

**Comment by toolchainx** [comment]
可以通过 https://dev.aliyun.com/detail.html?spm=5176.1972343.2.2.0UK76U&repoId=8525 的自定义代理配置或者扩展该镜像来支持
