### ISSUE TITLE
routing需要一个可配置的功能

### ISSUE THREAD

**Issue by lxepoo** [AliyunContainerService/Issues#24]
routing有部分的选项我们想自己定制，和霖华沟通后得知你们正在做，我只希望能满足一下几个：
1.配置最好能回滚
2.最好能够在容器里像数据卷一样，做个UI来配置控制，具体请参考RDS for mysql的配置界面。

以上如果不能实现，请忽略我。

**Comment by denverdino** [comment]
1. 能提供更多的信息吗？
2. 已经在计划中，会提供一个页面列出所有已经定义的路由规则和容器信息。您有什么具体需求吗？
