### ISSUE TITLE
logs服务是否可以不主动创建sls的project？

### ISSUE THREAD

**Issue by lxepoo** [AliyunContainerService/Issues#25]
当前sls已经商用并且收费，容器开通logs服务后，默认会创建一个project来完成日志收集相关的功能。

戒空说可以配置为自己的project，但是我仍然希望：

1.容器服务创建的project是否可以删除？
2.删除后是否会导致异常？

希望得到一个明确回复，谢谢。

**Comment by jzwlqx** [comment]
先回答后面两个问题
1. 可以删除
2. 删除后，只要不使用就不会有异常。不使用的意思是

```
a. 编排文件里不要出现label aliyun.log_store_* 或者
b. 出现label aliyun.log_store_*的同时，指定自己的project
```
