### ISSUE TITLE
能否不要自动创建SLB，改为触发式创建？

### ISSUE THREAD

**Issue by lxepoo** [AliyunContainerService/Issues#26]
一个集群，我们可能会对外服务，也可能会内提供服务（比如api类）

现在创建集群默认创建一个【公网SLB】，实时上我期望的是，在创建集群后，集群的设置里有一个按钮叫【创建并绑定SLB】，点击后可以创建公网SLB和内网SLB，创建完成后自动完成后端机绑定。这个按钮可以多次使用，从而创建N个SLB。另需要集群内可以显示已经创建并绑定的SLB列表。

我这个需求的目的 ：
1.一旦发生DDOS，进入黑洞，整个集群不能对外提供服务。在没有高防IP的情况下，我会选择换IP，但是现在换IP会很麻烦，要先创建一个SLB，所有后端需要重新绑定。

2.我的集群里可能有多个对外的产品，因为各种原因我不希望他们使用同一个IP地址，因为SEO、不严格的审核机制导致的舆论风险、太集中容易被攻击等。

3.一个集群，我们部署了一套API，这套API对内提供服务，供我们其他集群调用，因为现在跨集群通信有点烦，我们希望通过一个内网SLB来穿透，达到访问目的。但是又希望对外通服务，所以还需要一个SLB。

我想说的是，当下虽然可以通过手动创建SLB来完成上述说的一切功能，但是问题也带来，手动管理会比较麻烦而且每次添加机器都要手动调，这提高了出错率，我们希望是自动的。

**Comment by denverdino** [comment]
1. 很快我们就会把SLB作为可选项，在创建集群时可以选择创建，之后可以修改，解绑
2. >> 我的集群里可能有多个对外的产品，因为各种原因我不希望他们使用同一个IP地址，因为SEO、不严格的审核机制导致的舆论风险、太集中容易被攻击等。
   这个是否可以考虑部署多个集群，或者使用指定SLB为特定的应用提供服务？
3. >> 3.一个集群，我们部署了一套API，这套API对内提供服务，供我们其他集群调用，因为现在跨集群通信有点烦，我们希望通过一个内网SLB来穿透，达到访问目的。但是又希望对外通服务，所以还需要一个SLB。
   这个也可以考虑部署多个SLB，我们同时也在简化和支持自定义路由服务。

**Comment by menglingwei** [comment]
我们会提供SLB可选项的功能，届时可以绑定或者解绑SLB

**Comment by menglingwei** [comment]
目前已提供可选SLB功能，届时也支持了重新绑定SLB以及设置 routing domain
