### ISSUE TITLE
需要更新应用中部分服务的功能

### ISSUE THREAD

**Issue by perfeyhe** [AliyunContainerService/Issues#27]
```
如果我的一个应用中包含web-app-db三层服务，这组应用中只有app层会经常更新镜像（由于要更新代码，更新代码是通过将代码提交到github，通过webhook触发重新构建镜像），但目前阿里只提供了应用级别的重新部署功能，因此，一旦我需要更新了代码，只能在应用层重新部署，因而我的web、db层也会重新构建，但这不是我们想要的结果。
这样导致的问题是，用户为了规避容器更新带来的相互影响，只能将每一组服务都建立成独立的应用，而这样是否就失去了应用的意义？
```

**Comment by denverdino** [comment]
您的意思是web-app-db三层服务都的三个镜像是属于同一个代码仓库是吗，并且全部设置了自动重构？如果这样，三个镜像就会同时更新。所以当代码提交时，三个镜像就都会更新，如果设置了重新部署的功能会依次更新相关服务。

我的建议是如果您可以将db的镜像设置为非自动构建，这样只有手工触发才能重构镜像。这样db服务就不会更新了。

**Comment by perfeyhe** [comment]
三个镜像不在同一个仓库，只是属于同一个应用，但应用重新部署的时候会把应用下所有的服务全部重新构建一遍，没有办法设置只重新构建某一个服务

**Comment by denverdino** [comment]
重新部署只会更新那些镜像更新过的容器，和重启其他依赖的容器（使用容器连接）。如果compose模板设计合理，更新了app层，db应该不会重新更新或者重启

**Comment by perfeyhe** [comment]
恩，理解错误，已经测试过并不是所有容器都会更新，谢谢
