### ISSUE TITLE
自定义SLB规则模块有一处安全隐患

### ISSUE THREAD

**Issue by lxepoo** [AliyunContainerService/Issues#3]
背景：
我创建了一个应用，mongodb的镜像，我开启了27017端口，并且在自定义规则中设置了对应的规则为：
tcp://xxxxxx-cn-hangzhou-dg-a01:27017，应用和容器创建完成后能成功运行并正常使用。后来我考虑了一下27017容易被黑客扫描和利用，所以我改为了20001端口，改完后一切正常，也能使用。

但是我进入SLB控制台后，发现侦听端口处27017此条记录依旧存在，所以此处会带来一个安全隐患，当用户取消了自定义SLB后，老的记录却仍然有效。

**Comment by denverdino** [comment]
我们复查一下解绑定的逻辑

**Comment by toolchainx** [comment]
@lxepoo, 考虑到用户创建监听端口和删除监听端口形成闭环，后续我们不会帮助用户创建监听端口，而是将创建监听端口和删除监听端口的动作都交给用户来做。

**Comment by lxepoo** [comment]
明白

**Comment by toolchainx** [comment]
该问题已经解决，相应的文档也已经修改,参见https://help.aliyun.com/document_detail/26086.html?spm=5176.product9091095_25972.6.200.VlasSL#lb , 用户将slb创建好之后，绑定到容器服务 ，容器服务只做后端vm的绑定，其他设置，包括端口的设置均由用户自己通过openapi或者slb控制台完成。如有相关疑问请留言 @lxepoo
