### ISSUE TITLE
构建时间过长

### ISSUE THREAD

**Issue by FrostyLeaf** [AliyunContainerService/Issues#32]
最近一段时间经常出现构建时间过长的问题，稍不注意就是一两千秒，而且经常失败，请问是怎么回事呢？

**Comment by denverdino** [comment]
1. 如果从国外网站下载很多内容请考虑采用国内镜像
   比如 https://dev.aliyun.com/detail.html?repoId=3122 等提供了基于阿里云的apt和python镜像
2. 或者采用海外集群进行构建

如果还有问题，请开工单提供repo信息，构建日志，请开发同学帮助排查

谢谢
