### ISSUE TITLE
希望能够设定构建tag规则

### ISSUE THREAD

**Issue by masiqi** [AliyunContainerService/Issues#33]
比如代码库打tag名为v0.0.1自动构建tag为v0.0.1的镜像
谢谢

**Comment by susanna8930** [comment]
您好，现在在阿里云镜像服务上，支持打符合标准格式的tag，就触发自动构建的流程。tag类型需要符合 "release-v$version"的格式，比如，我打了 git tag -a release-v1.1.0 -m "Update ...." ;然后push至远程，git push origin --tags。则会触发镜像服务上的自动构建，帮您生成1.1.0的镜像版本。

非常抱歉，由于镜像服务这边暂时在进行前端改版，目前只能使用 "release-v$version"的格式，我们后续会提供页面，方便您设置。

**Comment by masiqi** [comment]
好的，谢谢！！！我试试
