### ISSUE TITLE
应用列表显示应用的描述

### ISSUE THREAD

**Issue by denverdino** [AliyunContainerService/Issues#4]
![image](https://cloud.githubusercontent.com/assets/409721/15278365/4ace6c28-1b4a-11e6-9553-f3f6b0b97d61.png)

**Comment by lxepoo** [comment]
创建应用时的应用描述，貌似写了没意义，后续操作无法显示，也无法修改。

**Comment by ddbmh** [comment]
@lxepoo 可以考虑将应用描述的前若干字符显示在应用列表。

**Comment by denverdino** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/409721/15675154/146a9776-2773-11e6-918a-08790ae9fac9.png)

**Comment by lxepoo** [comment]
可以的，但是我们自己创建的应用好像不会显示这些信息，是需要重新创建吗？

**Comment by denverdino** [comment]
另外如果是从镜像构建的应用，之前的实现有问题，需要重新创建。谢谢
