### ISSUE TITLE
根据正则来自动构建docker版本

### ISSUE THREAD

**Issue by shiningrise** [AliyunContainerService/Issues#40]
像hub.docker.com一样
The build rules below specify how to build your source into Docker images. The name can be a string or a regex. The Docker Tag name may contain variables. We currently support {sourceref}, which refers to the source branch/tag name. Show less

Scenario
Type
Name
Docker Tag Name
Matches
Docker Tag Built
Exact match
Branch
master
latest
master
latest
Match versions
Tag
/^[0-9.]+$/
release-{sourceref}
1.2.0
release-1.2.0
Trailing modifiers
Tag
/^[0-9.]+/
release-{sourceref}
1.2.0-rc
release-1.2.0-rc
如下 ：
https://hub.docker.com/r/shiningrise/docker-mono-apache/~/settings/automated-builds/

**Comment by denverdino** [comment]
https://www.alibabacloud.com/help/doc-detail/187479.htm
