### ISSUE TITLE
求：设置新机器加入集群后，可以执行一段设置好的初始化脚本

### ISSUE THREAD

**Issue by MooYoo** [AliyunContainerService/Issues#43]
设置新机器加入集群后，可以执行一段设置好的初始化脚本（主要用来宿主机的初始化，如改内核参数等。还可以调用阿里云api，将新机器加入RDS白名单等）

**Comment by BSWANG** [comment]
@MooYoo 可以使用[`aliyun.global`](https://help.aliyun.com/document_detail/26086.html#global)的标签保证新加入的机器能够调度初始化的容器到机器上，然后您就可以在容器中去做这些的配置。

**Comment by MooYoo** [comment]
@BSWANG 主要是有些东西只能在宿主机操作的，比如修改内核参数。
调用阿里云api，将新机器加入RDS白名单，这些确实可以考虑你说的这个方式，感谢

**Comment by BSWANG** [comment]
@MooYoo 好的，那我暂时先关闭这个Issue了，后续有相关的问题也可以随时在这个Issue中沟通。
