### ISSUE TITLE
求：rolling_updates可以批量更新

### ISSUE THREAD

**Issue by MooYoo** [AliyunContainerService/Issues#46]
aliyun.rolling_updates: "true"
使用了rolling_updates后，容器一多，发布/回滚时间会很长，我现在只有25个容器），发布时间超过3分钟。
有什么方案可以最小化停止服务时间，同时做到快速发布完成？后续会有80个容器，这个速度很难接受

这几比较急，早上发现故障回滚花了很长时间
比如可以考虑设置分多少批更新.比如分5批更新，每批同时更新的数量就是1/5

**Comment by jimmycmh** [comment]
需求已经收到，会安排开发。

**Comment by xianlubird** [comment]
Done 文档地址 https://help.aliyun.com/document_detail/48477.html

@MooYoo
