### ISSUE TITLE
容器服务的OpenApi的应用列表接口返回太多导致溢出

### ISSUE THREAD

**Issue by lxepoo** [AliyunContainerService/Issues#5]
我一个集群可能有几百个小应用，通过此接口获取数据时，不好分页，所有数据全量返回了。导致我的程序溢出，希望处理一下，有2个意见：

1.为此接口添加一个分页功能
2.为此接口添加一个返回信息规模的字段 ，可以选择性返回部分字段，如：id，名称，镜像，当前状态，创建时间，升级时间，容器数量

**Comment by denverdino** [comment]
关于2，已经提供过滤参数，请参见API文档。升级到最新的agent即可使用
https://help.aliyun.com/document_detail/26065.html
https://help.aliyun.com/document_detail/26073.html
