### ISSUE TITLE
希望镜像服务具有删除指定TAG的能力

### ISSUE THREAD

**Issue by thonatos** [AliyunContainerService/Issues#51]
- 背景
自动构建依赖tag，但是误操作后删除了git的tag，却在镜像服务中构建了版本，目前无法删除；这样比较浪费存储空间，同时也不利用管理版本

- 需求
希望镜像服务能提供：***删除指定tag的接口***

**Comment by denverdino** [comment]
https://www.alibabacloud.com/help/doc-detail/199249.htm
